### ISSUE TITLE
Switch token from param to bearer token and add public key encryption requirement!

### ISSUE THREAD

**Issue by stonegold546** [ISS-Analytics/canvas-lms-visualizations-api#2]
Passing the all important all powerful token as an argument rubs me the wrong way. Feel the same even if it's done via the authentication header.

**TODOs**:
- [x] Basic: Switch from param to bearer token.
- [x] Additional: Encrypt the token using our API's public key; we could offer this as an API service. This way, we only accept encrypted tokens for regular API requests, whether it's coming from our app or from an API user.

**Comment by soumyaray** [comment]
hear hear
